name: budget_app
description: A Flutter app for managing budgets and expenses.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  flutter_spinkit: ^5.2.0
  percent_indicator: ^4.2.3   # ✅ أضفنا المكتبة

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.png
    - assets/images/logo.jpg
    - assets/images/wallet.jpg
    - assets/images/avatar.png
    - assets/images/expense.png
    - assets/images/welcome.png
    - assets/images/profile.png
    # لو عندك أيقونات للتطبيق زي جوجل/فيسبوك/سبوتيفاي/نتفليكس ضيفها هنا:
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/icons/netflix.png
    - assets/icons/spotify.png
